### ISSUE TITLE
Switch wallet >> cannot connect wallet rpc

### ISSUE THREAD

**Issue by Azazel020** [loki-project/loki-electron-gui-wallet#115] opened 2020-01-19 08:56 UTC
**Describe the bug**
I have a open wallet and want to switch to another wallet. I`m selecting the other wallet, enter my password and after confirm I get an error message: Cannot connect to wallet-rpc

**To Reproduce**
1) Open the Electron wallet
2) Select and open wallet 1
3) Wait till you see a synced overview of your transactions
4) Select in the left upper corner the button 'switch wallet'
5) Select another wallet
6) enter password
7) now you will see the error message : Cannot connect to wallet-rpc

**Screenshots or Log files**
If applicable, add screenshots or Log files to help explain your problem.
![2020-01-19 09_54_57](https://user-images.githubusercontent.com/44430967/72677959-df605700-3aa1-11ea-8832-dba278e4148a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Electron v1.3.2

**Comment by Mikunj** [comment] 2020-01-19 21:34
Can you check if this occurs on 1.3.3?

**Comment by Azazel020** [comment] 2020-01-22 15:40
Updated the wallet and in 1.3.3 the same problem.
You first have to close the wallet before you can enter another wallet.

**Comment by Skelaton4** [comment] 2020-01-22 15:52
I can confirm I am also experiencing this issue with 1.3.3 on Windows 10.

**Comment by Azazel020** [comment] 2020-04-01 15:31
Updated the wallet to v1.4.0 but still the same error.

**Comment by Mikunj** [comment] 2020-04-01 21:51
Oh no :(
I'll keep digging around to see if i can get this to happen and fix it if i can

**Comment by Mikunj** [comment] 2020-04-07 23:42
I got this to happen on 1.4.1 but i can't find a solid reproducible case. if you find one let me know so we can dig into it further.

**Comment by Azazel020** [comment] 2020-04-08 17:24
You need to have a Electron wallet with multiple wallets in this wallet. Open wallet 1 and let come in sync. Then try to swith to wallet 2. You will have the same error

**Comment by saschaseewald** [comment] 2020-05-31 12:02
Still have the same problem on 1.4.3 ...

**Comment by Mikunj** [comment] 2020-05-31 22:37
The problem seems to be originating from the `wallet-rpc` itself. I've passed on the bug to the daemon dev.

**Comment by LokiNugget** [comment] 2020-07-14 13:27
Any updates? v1.4.3 for OSX is consistantly giving me this issue.

**Comment by Mikunj** [comment] 2020-07-15 00:33
This issue will be resolved with the next lokid release but that might take a month or two to get released. In the meantime, I'm going to test out a few workarounds which if successful will make it into a wallet release.

**Closed** 2020-07-17 03:31 UTC
Labels: bug
